### ISSUE TITLE
атропоморфні чи ні ?

### ISSUE THREAD

**Issue by albussiverus** [iGuiDES/hillel_py_basic#1]
https://github.com/iGuiDES/hillel_py_basic/blob/7c720c631342c74900bccb9fd361f87f671bbcd1/hw_05/task_2.py#L9

<img width="832" alt="image" src="https://github.com/iGuiDES/hillel_py_basic/assets/142038191/4778c4b0-8a80-48c6-b252-f15d95437af6">

25 * 25 = 625  -  де 25 є осанніми циврами в числі 625  - атропоморфне !
26 * 26 = 676 - 26 не є остнніми цифрами в 676 - не аропоморфне !

**Comment by iGuiDES** [comment]
Зрозумів свою помилку, завдання переробив
