### ISSUE TITLE
Не те  що очікувалось у задачі 

### ISSUE THREAD

**Issue by albussiverus** [iGuiDES/hillel_py_basic#2]
https://github.com/iGuiDES/hillel_py_basic/blob/7c720c631342c74900bccb9fd361f87f671bbcd1/hw_05/task_4.py#L1
<img width="501" alt="image" src="https://github.com/iGuiDES/hillel_py_basic/assets/142038191/4967f6c5-14d2-4462-81f6-8c89ca9bb1d1">

я бачу як позїдало пробіли в задачі 4 і тому важко зрозуміти сами приклади 4 задчі також 
Що там очікувалось ?
якщо я введу число 
наприклад : 50 
очікуються квадрити чисел від 0 які самі менші за число 50 

10 1 4 9 16 25 36 49

**Comment by iGuiDES** [comment]
Так, все вірно, я щось трошки не так зрозумів і нашвидив в результаті
Переробив завдання, дякую за підказку
