### ISSUE TITLE
Треба перевіряти перед здачею роботи!!!!!

### ISSUE THREAD

**Issue by albussiverus** [iGuiDES/hillel_py_basic#3]
https://github.com/iGuiDES/hillel_py_basic/blob/137da479f26df29e9b94d0218cb0bcbd7121378d/hw_05/task_2.py#L6
Тут або один знак * або i ** 2 
бо інакше виходить піднесення до степеню i
i ** i  тобто 8 ** 8 чи 10 ** 10 
але то ж не квадрат числа!!!!!

**Comment by iGuiDES** [comment]
Так точно, перепрошую, виправляв помилки на коліна несучи службу 
На майбутнє, буду більш уважним, дякую
