### ISSUE TITLE
а можна було просто конвертувати список до множини 

### ISSUE THREAD

**Issue by albussiverus** [iGuiDES/hillel_py_basic#4]
https://github.com/iGuiDES/hillel_py_basic/blob/3984d7da6ab443f4c7dba40ff3c4e47f071de614/hw_08/task_2.py#L7
https://github.com/iGuiDES/hillel_py_basic/blob/3984d7da6ab443f4c7dba40ff3c4e47f071de614/hw_08/task_2.py#L10
можна було б замінити переведенням до типу данних set 
set1 = set(list1)

**Comment by iGuiDES** [comment]
Хм, згоден, цікава думка
Не подумав, що можна опустити цикли

<img width="808" alt="Screenshot 2023-10-20 at 12 57 48" src="https://github.com/iGuiDES/hillel_py_basic/assets/49126669/ff68c9a6-420d-400a-9b45-dc5c32eab0fe">

Виправив, дякую
